import Head from "next/head"
import { Footer } from "./Footer"
import { Navbar } from "./Navbar"

export default function PageLayout({ children, ...props }) {
  const { title, principal, fondo } = props

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Navbar></Navbar>
      <main>
        <div className="flex place-content-center mt-20">
          <h1 className="font-bold text-3xl">{principal}</h1>
        </div>
        {children}
      </main>
      <Footer bottom={fondo} />
    </>
  )
}

PageLayout.defaultProps = {
  principal: "",
  fondo: false,
  title: "My Criptos",
  home: false,
}
